name: Repo Policy Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  call-repo-policy-check:
    uses: sshedge71/qcom-reusable-workflows/.github/workflows/reusable-repo-policy-check.yml@10969e0bbb04ed806789998a89bedfad6447b9ab
