name: Qualcomm Preflight Checks Orchestrator Reusable Workflow

on:
  workflow_call:
    inputs:
      enable-semgrep-scan:
        required: false
        type: boolean
        default: true
      semgrep-cli-options:
        required: false
        type: string
        default: '--config auto'
      enable-repolinter-check:
        required: false
        type: boolean
        default: true
      enable-repo-policy-check:
        required: false
        type: boolean
        default: true
      enable-copyright-license-check:
        required: false
        type: boolean
        default: true
      enable-commit-email-check:
        required: false
        type: boolean
        default: true
      enable-dependency-review:
        required: false
        type: boolean
        default: true
      enable-commit-msg-check:
        required: false
        type: boolean
        default: false
      commit-msg-check-extra-options:
        required: false
        type: string
        default: '{}'
        description: 'Extra options as YAML/JSON object string, e.g., {"body-char-limit": 60, "sub-char-limit": 50, "check-blank-line": true}'
      enable-armor-checkers:
        required: false
        type: boolean
        default: false
      armor-checker-options:
        required: false
        type: string
        default: ''
        description: 'ARMOR checker options as JSON string.e.g., {"build-script":"ci/build.sh","runs-on":{"group":"<group>","labels":["<l1>","<l2>"]}}'

jobs:
  semgrep-scan:
    if: ${{ inputs.enable-semgrep-scan }}
    name: Semgrep Scan
    uses: ./.github/workflows/reusable-semgrep-scan.yml
    with:
      semgrep-cli-options: ${{ inputs.semgrep-cli-options }}
    permissions:
      contents: read
      security-events: write

  dependency-review:
    if: ${{ inputs.enable-dependency-review }}
    name: Dependency Review
    uses: ./.github/workflows/reusable-dependency-review.yml
    permissions:
      contents: read

  repolinter-check:
    if: ${{ inputs.enable-repolinter-check }}
    name: Repolinter Check
    uses: ./.github/workflows/reusable-repolinter-check.yml
    permissions:
      contents: read

  repo-policy-check:
    if: ${{ inputs.enable-repo-policy-check }}
    name: Repository Policy Check
    uses: ./.github/workflows/reusable-repo-policy-check.yml
    permissions:
      contents: read

  copyright-license-check:
    if: ${{ inputs.enable-copyright-license-check }}
    name: Copyright and License Check
    uses: ./.github/workflows/reusable-copyright-license-check.yml
    permissions:
      contents: read

  commit-email-check:
    if: ${{ inputs.enable-commit-email-check }}
    name: Commit Email Check
    uses: ./.github/workflows/reusable-commit-emails-check.yml
    permissions:
      contents: read

  commit-msg-check:
    if: ${{ inputs.enable-commit-msg-check }}
    name: Commit Message Check
    uses: ./.github/workflows/reusable-commit-msg-check.yml
    with:
      extra-options: ${{ inputs.commit-msg-check-extra-options }}    
    permissions:
      contents: read

  armor-checkers:
    if: ${{ inputs.enable-armor-checkers }}
    name: ARMOR Compatibility Checkers
    uses: qualcomm/armor-checkers/.github/workflows/armor-checker.yml@v1
    with:
      armor-checker-options: ${{ inputs.armor-checker-options }}
    permissions:
      contents: read
